cloud:
  aws:
    credentials:
      access-key: AKIAQJQUBU4MWSFZIQ7V
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: fileupload1-test


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 5000